#!/bin/bash

case $1 in
  off)
    /usr/bin/xmodmap -e "pointer = default"
    /usr/bin/xmodmap -e "keycode 117 = Menu"
  ;;
  *)
    /usr/bin/xmodmap -e "pointer = 1 2 13 4 5 6 7 8 9 10 11 12 3"
    /usr/bin/xmodmap -e "keycode 117 ="
  ;;
esac